version: '3.8'
services:
  db:
    image: mysql:8.0.33
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: user
      MYSQL_DATABASE: admin
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
    volumes:
      - ./api/db/migrations:/migrations
